const logotext = "I'm A Flower";
const hoverlogotext ="ㄴㅏㄴㅎㅗㅏ";
const meta = {
    title: "I'm A Flower",
    description: "I’m John Doe data scientist _ Full stack devloper,currently working in Berlin",
};

const dataabout = {
    title: "abit about my self",
    aboutme: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis dolor id ligula semper elementum feugiat pretium nulla. Nunc non commodo dolor. Nunc mollis dignissim facilisis. Morbi ut magna ultricies.",
};

const dataportfolio = [
{
    id: 1,
    icon: 'web',
    mockup: '',
    dir: '',
    name: '',
    project: 'Web Project',
    skills: 'Spring Boot',
    description: '',
    link: '',
    main_img: '',
},
{
    id: 2,
    icon: 'web',
    mockup: 'web',
    dir: '',
    name: '',
    project: 'App Project',
    skills: 'Spring Boot',
    description: '',
    link: '',
    main_img: '',
},

{
    id: 3,
    icon: "app",
    mockup: 'app',
    dir: 'menuselection',
    name: '밥뭐먹잰',
    project: 'App Project',
    skills: 'Android Studio, Java',
    description: '랜덤으로 메뉴 선택을 도와주는 앱 개발 version. 제주대',
    link: 'https://github.com/nhwa/menuselection-androidstudio-app',
    main_img: {src: "menuselection.png", alt: "밥뭐먹잰"},
},
{   id: 4,
    icon: "design",
    mockup: 'app',
    dir: 'daybylist',
    name: "Day By List",
    project: "UI/UX Design",
    skills: "Adobe XD, Photoshop, Illustrator",
    description: "To-Do List 관리 앱 UX/UI 설계",
    link: "https://github.com/nhwa/daybylist-xd-ui-ux",
    main_img: {src: "daybylist1.png", alt: "daybylist"},
},
{   
    id: 5,
    icon: "web",
    mockup: 'web',
    dir: 'spark',
    name: "Spark Design Awards",
    project: "UI/UX Design",
    description: "Concept 2018 FINALLIST",
    skills: "Photoshop, Illustrator, Rhino",
    link: '',
    main_img: {src: "spark1.jpg", alt: "spark design awards"},
},
{   id: 6,
    icon: "web",
    mockup: 'web',
    dir: 'dreamers',
    name: "Dreamers",
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript, PHP, Apache, Mysql",
    description: "유저가 각자 자신의 버킷리스트를 공유하는 커뮤니티 웹 개발 프로젝트",
    link: "https://github.com/nhwa/dreamers-php-frontend-backend",
    main_img: {src: "dreamers1.png", alt: "dreamers"},
},

{   id: 7,
    icon: "web",
    mockup: 'web',
    dir: 'silvermedal',
    name: "Silver Medal",
    project: "Contest",
    skills: "Photoshop, HTML5, CSS, JavasCript, PHP, Apache, Mysql",
    description: "제주도 지방기능경기대회 은메달 수상",
    link: "http://www.jejumaeil.net/news/articleView.html?idxno=178584",
    main_img: {src: "silvermedal.png", alt: "silvermedal"},
},
{   id: 8,
    icon: "design",
    mockup: 'book',
    dir: 'arablewhitepaper',
    name: "Arable Whitepaper",
    project: "Design Project",
    skills: "Photoshop, Illustrator, Word",
    description: "Blockchain-based Arable Metaverse Platform Whitepaper Design",
    link: "docs/arable_ko.pdf",
    main_img: {src: "arablewhitepaper1.png", alt: "arable whitepaper"},
},
{   id: 9,
    icon: "app",
    mockup: 'app',
    dir: 'jnubus',
    name: "JNU BUS",
    project: "App Project",
    skills: "Android Studio , JAVA",
    description: "제주대학교 교내 셔틀버스 안내 App Project",
    link: "https://github.com/nhwa/jnubus-androidstudio-app",
    main_img: {src: "jnubus1.png", alt: "jnubus"},
},
{   id: 10,
    icon: "app",
    mockup: 'app',
    dir: 'moberz',
    name: "MOBERZ",
    project: "App Project",
    skills: "Android Studio , JAVA",
    description: "축제 정보 공유 App 프로젝트",
    link: "https://github.com/nhwa/moberz-androidstudio-app",
    main_img: {src: "moberz.png", alt: "Moberz"},
},
{   id: 11,
    icon: "ai",
    mockup: 'web',
    dir: 'predictionprices',
    name: "Prediction Prices AI Project",
    project: "AI Project",
    skills: "Python - pandas, numpy, matplotlib 패키지",
    description: "지역별 서비스가격을 통한 물가 예측 AI Project",
    link: "https://github.com/nhwa/predictprices-python-ai",
    main_img: {src: "predictionprices.png", alt: "predictionprices"},
},
{   id: 12,
    icon: "ai",
    mockup: 'web',
    dir: 'datavisualization',
    name: "Data Visualization Project",
    project: "AI Project",
    skills: "Python - pandas, numpy, matplotlib 패키지",
    description: "한국,중국관광객 csv 데이터를 활용한 제주 관광산업 카드 이용 현황 분석 Project",
    link: "https://github.com/nhwa/data-visualization-python-bigdata",
    main_img: {src: "datavisualization1.png", alt: "datavisualization"},
},
{   id: 13,
    icon: "web",
    mockup: 'app',
    dir: 'jejufreewifi',
    name: "JEJU FREE WIFI",
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript",
    description: "제주 공공 Wi-Fi 통합 관제 시스템 구축 Project",
    link: "#",
    main_img: {src: "jejufreewifi.png", alt: "jejufreewifi"},
},
{   id: 14,
    icon: "web",
    mockup: 'list',
    dir: 'paullab',
    name: "Interactive Web Publishing",
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript",
    description: "바울랩ICT Subpage Publishing Project",
    link: '',
    main_img: [{src: "paullab1.png", alt: "paullab1", link: "https://paullab.co.kr/referenceroom.html"},{src: "paullab2.png", alt: "paullab2",link:"https://paullab.co.kr/halloffame.html"}],
},
{   id: 15,
    icon: "app",
    mockup: 'app',
    dir: 'myday',
    name: "Myday : 오늘을 기록하다",
    project: "Web Project",
    skills: "Android Studio , JAVA , Firebase",
    description: "매일을 기록하는 일기장 App 프로젝트",
    link: "https://github.com/nhwa/MyDay",
    main_img: {src: "myday1.png", alt: "myday"},
},
{   id: 16,
    icon: "web",
    mockup: 'web',
    dir: 'startfe',
    name: "START-FE",
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript, React",
    description: "고급웹개발론 - 실습 저장소",
    link: "https://github.com/nhwa/startfe-javascript-frontend",
    main_img: {src: "startfe.png", alt: "start-fe"},
},
{   id: 17,
    icon: "web",
    mockup: 'web',
    dir: 'daumsearch',
    name: "Daum 1boon 서비스 만들기",
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript",
    description: "kakao 1boon 사이트 url을 통해 가져온 데이터를 활용하여 1boon 서비스 구축",
    link: "https://github.com/nhwa/daumsearch-javascript-frontend",
    main_img: {src: "daumsearch.png", alt: "daumsearch"},
},
{   id: 18,
    icon: "web",
    mockup: 'book',
    dir: 'kipee',
    name: "2017 학술발표대회 논문집 수록 ",
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript",
    description: "자기 주도 학습 의욕향상 시뮬레이션, 자기주도형 학습 매체 개발 총 두건 수록",
    link: "docs/kipee.pdf",
    main_img: {src: "kipee.jpg", alt: "kipee"},
},
];


const introdata = {
    title: "I’m John Doe",
    animated: {
        first: "I love coding",
        second: "I code cool websites",
        third: "I develop mobile apps",
    },
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at nisl euismod urna bibendum",
    your_main_img_url: "https://images.unsplash.com/photo-1514790193030-c89d266d5a9d",
};

const socialprofils = {
    github: "https://github.com",
    youtube: "https://youtube.com",
    notion: "https://notion.com"
};
export {
    meta,
    logotext,
    hoverlogotext,
    socialprofils,
    dataportfolio,
    introdata
};
