const logotext = "I'm A Flower";
const hoverlogotext ="ㄴㅏㄴㅎㅗㅏ";
const meta = {
    title: "I'm A Flower",
  };

const about = {
    profile: "profile.jpg",
    title: "abit about my self",
    aboutme: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis dolor id ligula semper elementum feugiat pretium nulla. Nunc non commodo dolor. Nunc mollis dignissim facilisis. Morbi ut magna ultricies.",
};
const worktimeline = [{
        jobtitle: "Designer of week",
        where: "YAdfi",
        date: "2020",
    },
    {
        jobtitle: "Designer of week",
        where: "Jamalya",
        date: "2019",
    },
    {
        jobtitle: "Designer of week",
        where: "ALquds",
        date: "2019",
    },
];

const skills = [{
        name: "Python",
        value: 90,
    },
    {
        name: "Djano",
        value: 85,
    },
    {
        name: "Javascript",
        value: 80,
    },
    {
        name: "React",
        value: 60,
    },
    {
        name: "Jquery",
        value: 85,
    },
];

const services = [{
        title: "UI & UX Design",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at nisl euismod urna bibendum sollicitudin.",
    },
    {
        title: "Mobile Apps",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at nisl euismod urna bibendum sollicitudin.",
    },
    {
        title: "Wordpress Design",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at nisl euismod urna bibendum sollicitudin.",
    },
];

const dataportfolio = [
{
    id: 1,
    icon: 'web',
    mockup: 'web',
    dir: 'diveflashweb',
    name: 'Diveflash Web Developement',
    work: 'Personal',
    project: 'Web Project',
    skills: "HTML5, CSS, JavasCript, React",
    description: '©Diveflash Web 구축',
    link: 'https://diveflash.com/',
    main_img: {src: "diveflashweb.png", alt: "diveflashweb"},
    card_img: {src: "diveflashweb_card.png", alt: "diveflashweb"},
},   
{
    id: 2,
    icon: 'web',
    mockup: 'web',
    dir: 'arable',
    name: 'Arable Web Developement',
    work: 'Personal',
    project: 'Web Project',
    skills: "HTML5, CSS, JavasCript",
    description: 'Arable Web Developement',
    link: 'https://nhwa.github.io/arable-javascript-frontend/index.html',
    main_img: {src: "arable.png", alt: "arable"},
    card_img: {src: "arable_card.png", alt: "arable"},
},
{
    id: 3,
    icon: "app",
    mockup: 'app',
    dir: 'menuselection',
    name: '밥뭐먹잰',
    work: 'Personal',
    project: 'App Project',
    skills: 'Android Studio, Java',
    description: '랜덤으로 메뉴 선택을 도와주는 앱 개발 version. 제주대',
    link: 'https://github.com/nhwa/menuselection-androidstudio-app',
    main_img: {src: "menuselection.png", alt: "밥뭐먹잰"},
    card_img: {src: "menuselection.png", alt: "밥뭐먹잰"},
},
{   id: 4,
    icon: "design",
    mockup: 'app',
    dir: 'daybylist',
    name: "Day By List",
    work: 'Personal',
    project: "UI/UX Design",
    skills: "Adobe XD, Photoshop, Illustrator",
    description: "To-Do List 관리 앱 UX/UI 설계",
    link: "https://github.com/nhwa/daybylist-xd-ui-ux",
    main_img: {src: "daybylist.png", alt: "daybylist"},
    card_img: {src: "daybylist.png", alt: "daybylist"},
},
{   
    id: 5,
    icon: "web",
    mockup: 'web',
    dir: 'spark',
    name: "Spark Design Awards",
    work: 'Team',
    project: "UI/UX Design",
    description: "Concept 2018 FINALLIST",
    skills: "Photoshop, Illustrator, Rhino",
    link: "docs/spark.pdf",
    main_img: {src: "spark.jpg", alt: "spark design awards"},
    card_img: {src: "spark_card.jpg", alt: "spark design awards"},
    
},
{   id: 6,
    icon: "web",
    mockup: 'web',
    dir: 'dreamers',
    name: "Dreamers",
    work: 'Team',
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript, PHP, Apache, Mysql",
    description: "유저가 각자 자신의 버킷리스트를 공유하는 커뮤니티 웹 개발 프로젝트",
    link: "https://github.com/nhwa/dreamers-php-frontend-backend",
    main_img: {src: "dreamers.png", alt: "dreamers"},
    card_img: {src: "dreamers.png", alt: "dreamers"},
},

{   id: 7,
    icon: "web",
    mockup: 'web',
    dir: 'silvermedal',
    name: "Silver Medal",
    work: 'Personal',
    project: "Contest",
    skills: "Photoshop, HTML5, CSS, JavasCript, PHP, Apache, Mysql",
    description: "제주도 지방기능경기대회 은메달 수상",
    link: "http://www.jejumaeil.net/news/articleView.html?idxno=178584",
    main_img: {src: "silvermedal.png", alt: "silvermedal"},
    card_img: {src: "silvermedal_card.png", alt: "silvermedal"},
},
{   id: 8,
    icon: "design",
    mockup: 'book',
    dir: 'arablewhitepaper',
    name: "Arable Whitepaper",
    work: 'Team',
    project: "Design Project",
    skills: "Photoshop, Illustrator, Word",
    description: "Blockchain-based Arable Metaverse Platform Whitepaper Design",
    link: "docs/arable_ko.pdf",
    main_img: {src: "arablewhitepaper.png", alt: "arable whitepaper"},
    card_img: {src: "arablewhitepaper.png", alt: "arable whitepaper"},
},
{   id: 9,
    icon: "app",
    mockup: 'app',
    dir: 'jnubus',
    name: "JNU BUS",
    work: 'Team',
    project: "App Project",
    skills: "Android Studio , JAVA",
    description: "제주대학교 교내 셔틀버스 안내 App Project",
    link: "https://github.com/nhwa/jnubus-androidstudio-app",
    main_img: {src: "jnubus.png", alt: "jnubus"},
    card_img: {src: "jnubus.png", alt: "jnubus"},
},
{   id: 10,
    icon: "app",
    mockup: 'app',
    dir: 'moberz',
    name: "MOBERZ",
    work: 'Team',
    project: "App Project",
    skills: "Android Studio , JAVA",
    description: "축제 정보 공유 App 프로젝트",
    link: "https://github.com/nhwa/moberz-androidstudio-app",
    main_img: {src: "moberz.png", alt: "Moberz"},
    card_img: {src: "moberz.png", alt: "Moberz"},
},
{   id: 11,
    icon: "ai",
    mockup: 'web',
    dir: 'predictionprices',
    name: "Prediction Prices AI Project",
    work: 'Personal',
    project: "AI Project",
    skills: "Python - pandas, numpy, matplotlib 패키지",
    description: "지역별 서비스가격을 통한 물가 예측 AI Project",
    link: "https://github.com/nhwa/predictprices-python-ai",
    main_img: {src: "predictionprices.png", alt: "predictionprices"},
    card_img: {src: "predictionprices_card.png", alt: "predictionprices"},
},
{   id: 12,
    icon: "ai",
    mockup: 'web',
    dir: 'datavisualization',
    name: "Data Visualization Project",
    work: 'Personal',
    project: "AI Project",
    skills: "Python - pandas, numpy, matplotlib 패키지",
    description: "한국,중국관광객 csv 데이터를 활용한 제주 관광산업 카드 이용 현황 분석 Project",
    link: "https://github.com/nhwa/data-visualization-python-bigdata",
    main_img: {src: "datavisualization.png", alt: "datavisualization"},
    card_img: {src: "datavisualization_card.png", alt: "datavisualization"},
},
{   id: 13,
    icon: "web",
    mockup: 'app',
    dir: 'jejufreewifi',
    name: "JEJU FREE Wi-Fi Publishing Project",
    work: 'Personal',
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript",
    description: "제주 공공 Wi-Fi 통합 관제 시스템 구축 Project",
    link: "https://github.com/nhwa/jejufreewifi-html-frontend",
    main_img: {src: "jejufreewifi.png", alt: "jejufreewifi"},
    card_img: {src: "jejufreewifi.png", alt: "jejufreewifi"},
},
{   id: 14,
    icon: "web",
    mockup: 'list',
    dir: 'paullab',
    name: "Interactive Web Publishing",
    work: 'Personal',
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript",
    description: "바울랩ICT Subpage Publishing Project",
    link: '',
    main_img: [{src: "paullab1.png", alt: "paullab1", link: "https://paullab.co.kr/referenceroom.html"},{src: "paullab2.png", alt: "paullab2",link:"https://paullab.co.kr/halloffame.html"}],
    card_img: {src: "paullab_card.png", alt: "paullab"},
},
{   id: 15,
    icon: "app",
    mockup: 'app',
    dir: 'myday',
    name: "Myday : 오늘을 기록하다",
    work: 'Team',
    project: "Web Project",
    skills: "Android Studio , JAVA , Firebase",
    description: "매일을 기록하는 일기장 App 프로젝트",
    link: "https://github.com/nhwa/MyDay",
    main_img: {src: "myday.png", alt: "myday"},
    card_img: {src: "myday.png", alt: "myday"},
},
{   id: 16,
    icon: "web",
    mockup: 'web',
    dir: 'startfe',
    name: "START-FE",
    work: 'Personal',
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript, React",
    description: "고급웹개발론 - Frontend",
    link: "https://github.com/nhwa/startfe-javascript-frontend",
    main_img: {src: "startfe.png", alt: "start-fe"},
    card_img: {src: "startfe_card.png", alt: "start-fe"},
},
{   id: 17,
    icon: "web",
    mockup: 'web',
    dir: 'daumsearch',
    name: "Daum 1boon 서비스 만들기",
    work: 'Personal',
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript",
    description: "kakao 1boon 사이트 url을 통해 가져온 데이터를 활용하여 1boon 서비스 구축",
    link: "https://github.com/nhwa/daumsearch-javascript-frontend",
    main_img: {src: "daumsearch.png", alt: "daumsearch"},
    card_img: {src: "daumsearch_card.png", alt: "daumsearch"},
},
{   id: 18,
    icon: "web",
    mockup: 'book',
    dir: 'kipee',
    name: "2017 학술발표대회 논문집 수록",
    work: 'Team',
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript",
    description: "자기 주도 학습 의욕향상 시뮬레이션, 자기주도형 학습 매체 개발 총 두건 수록",
    link: "docs/kipee.pdf",
    main_img: {src: "kipee.jpg", alt: "kipee"},
    card_img: {src: "kipee.jpg", alt: "kipee"},
},
{   id: 19,
    icon: "web",
    mockup: 'web',
    dir: 'beforeportfolio',
    name: "Before Portfolio",
    work: 'Personal',
    project: "Web Project",
    skills: "HTML5, CSS, JavasCript",
    description: "성장을 위한 발판",
    link: "https://nhwa.github.io/beforeportfolio_html_frontend/main.html",
    main_img: {src: "beforeportfolio.png", alt: "beforeportfolio"},
    card_img: {src: "beforeportfolio_card.png", alt: "beforeportfolio"},
},
{   id: 20,
    icon: "app",
    mockup: 'web',
    dir: 'diveflashfilter',
    name: "Diveflash Filter App",
    work: 'Team',
    project: "App Project",
    skills: "Flutter, Dart, C++, C, FireBase",
    description: "후보정 이미지 필터링 알고리즘 수중 사진 보정 앱 개발",
    link: "https://play.google.com/store/apps/details?id=com.killerwhale.Diveflash",
    main_img: {src: "diveflashfilter.png", alt: "diveflashfilter"},
    card_img: {src: "diveflashfilter_card.png", alt: "diveflashfilter"},
},
{   id: 21,
    icon: "app",
    mockup: 'web',
    dir: 'diveflashsns',
    name: "Diveflash SNS App",
    work: 'Team',
    project: "App Project",
    skills: "Flutter, Dart",
    description: "Diveflash 다이버 전용 SNS 앱 개발",
    link: "https://xd.adobe.com/view/d738d4a1-e186-402d-8a08-80c27e63e38b-826b/grid",
    main_img: {src: "diveflashsns.png", alt: "diveflashsns"},
    card_img: {src: "diveflashsns_card.png", alt: "diveflashsns"},
},
{   id: 22,
    icon: "app",
    mockup: 'web',
    dir: 'diveflashfilter',
    name: "Diveflash Filter App",
    work: 'Team',
    project: "App Project",
    skills: "Flutter, Dart, C++, C, FireBase",
    description: "",
    link: "https://play.google.com/store/apps/details?id=com.killerwhale.Diveflash",
    main_img: {src: "diveflashsns.png", alt: "diveflashsns"},
    card_img: {src: "diveflashsns_card.png", alt: "diveflashsns"},
},
];

const contactConfig = {
    YOUR_EMAIL: "devnhwa@gmail.com",
    YOUR_FONE: "+82 10 - 5015 - 4038",
    description: "언제든지 연락주세요 :) ",
    YOUR_SERVICE_ID: "service_f03osod",
    YOUR_TEMPLATE_ID: "template_59eg0xd",
    YOUR_USER_ID: "07BHjcjXXPnCqPtM0",
};

const socialprofils = {
    github: "https://github.com/nhwa",
    youtube: "https://www.youtube.com/channel/UCbr3j7VSvgNMnwpTII45vag",
    notion: "https://devnhwa.notion.site/I-m-A-Flower-a137ceae4d454de2a75b7650971ecb5f"
};
export {
    meta,
    logotext,
    hoverlogotext,
    about,
    worktimeline,
    skills,
    services,
    socialprofils,
    dataportfolio,
    contactConfig,
};
